name: debt_pal_arabic_v1
description: Arabic debt ledger app.
publish_to: "none"

version: 1.0.7+8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  audioplayers: ^6.0.0
  google_mobile_ads: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/coin.wav
    - assets/sounds/delete.wav
    - assets/sounds/settle.wav
