import 'dart:convert';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:share_plus/share_plus.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

const darkBg = Color(0xFF20242B);
const darkPanel = Color(0xFF2B3038);
const darkPanel2 = Color(0xFF343A44);
const redSoft = Color(0xFFFF5A6D);
const greenSoft = Color(0xFF55E36A);
const orangeSoft = Color(0xFFFF684A);
const yellowSoft = Color(0xFFFFC85A);
const blueSoft = Color(0xFF5EA0FF);
const cyanSoft = Color(0xFF28D4DD);
const whiteSoft = Color(0xFFFFF4D8);
const textMain = Color(0xFFFFF2D6);
const textSoft = Color(0xFFB7B7B7);
const divider = Color(0xFF3D444E);

String money(double v) => v == v.roundToDouble() ? v.toStringAsFixed(0) : v.toStringAsFixed(2);
String dateOnly(int ms){ final d=DateTime.fromMillisecondsSinceEpoch(ms); String t(int n)=>n.toString().padLeft(2,'0'); return '${d.year}/${t(d.month)}/${t(d.day)}'; }
String ago(int ms){ final diff=DateTime.now().difference(DateTime.fromMillisecondsSinceEpoch(ms)); if(diff.inMinutes<1)return 'الآن'; if(diff.inMinutes<60)return 'منذ ${diff.inMinutes} دقيقة'; if(diff.inHours<24)return 'منذ ${diff.inHours} ساعة'; if(diff.inDays<30)return 'منذ ${diff.inDays} يوم'; return dateOnly(ms); }
const admobBannerUnitId = 'ca-app-pub-3082968903080396/5279353190';

Future<void> appFeedback(String fileName) async {
  if (!Store.I.sounds) return;

  try {
    HapticFeedback.lightImpact();
  } catch (_) {}

  try {
    final player = AudioPlayer();
    await player.setPlayerMode(PlayerMode.lowLatency);
    await player.setReleaseMode(ReleaseMode.release);
    await player.setVolume(1.0);
    await player.play(AssetSource('sounds/$fileName'));
  } catch (_) {
    // If audio is blocked on an old device, vibration still works.
  }
}

void main() async { WidgetsFlutterBinding.ensureInitialized(); await Store.I.load(); runApp(const DebtApp()); }

class DebtApp extends StatelessWidget{ const DebtApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'دفتر الديون',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:darkBg,colorScheme:ColorScheme.fromSeed(seedColor:orangeSoft,brightness:Brightness.dark)),home:const Directionality(textDirection:TextDirection.rtl,child:HomeScreen())); }

class AdMobBanner extends StatefulWidget{ const AdMobBanner({super.key}); @override State<AdMobBanner> createState()=>_AdMobBannerState(); }
class _AdMobBannerState extends State<AdMobBanner>{ BannerAd? ad; bool loaded=false; @override void initState(){ super.initState(); WidgetsBinding.instance.addPostFrameCallback((_)=>loadAd()); } Future<void> loadAd() async{ try{ await MobileAds.instance.initialize(); final banner=BannerAd(adUnitId:admobBannerUnitId,size:AdSize.banner,request:const AdRequest(),listener:BannerAdListener(onAdLoaded:(_){if(mounted)setState(()=>loaded=true);},onAdFailedToLoad:(failedAd,error){failedAd.dispose(); if(mounted)setState(()=>loaded=false);})); ad=banner; await banner.load(); }catch(_){ ad?.dispose(); ad=null; if(mounted)setState(()=>loaded=false); } } @override void dispose(){ ad?.dispose(); super.dispose(); } @override Widget build(BuildContext context){ if(!loaded||ad==null)return const SizedBox.shrink(); return Container(height:ad!.size.height.toDouble(),width:double.infinity,alignment:Alignment.center,margin:const EdgeInsets.fromLTRB(14,8,14,8),child:SizedBox(width:ad!.size.width.toDouble(),height:ad!.size.height.toDouble(),child:AdWidget(ad:ad!))); }}

enum DebtType { lent, borrowed }

class Person{ String id,name; int createdAt; Person(this.id,this.name,this.createdAt); Map<String,dynamic> toJson()=>{'id':id,'name':name,'createdAt':createdAt}; factory Person.fromJson(Map<String,dynamic> j)=>Person(j['id']??'',j['name']??'',j['createdAt']??DateTime.now().millisecondsSinceEpoch); }
class Entry{ String id,personId,category,note; DebtType type; double amount,settledAmount; int createdAt; int? dueAt; bool settled; Entry({required this.id,required this.personId,required this.type,required this.amount,required this.settledAmount,required this.category,required this.note,required this.createdAt,this.dueAt,this.settled=false}); double get remaining => max(0, amount-settledAmount); Map<String,dynamic> toJson()=>{'id':id,'personId':personId,'type':type.name,'amount':amount,'settledAmount':settledAmount,'category':category,'note':note,'createdAt':createdAt,'dueAt':dueAt,'settled':settled}; factory Entry.fromJson(Map<String,dynamic> j)=>Entry(id:j['id']??'',personId:j['personId']??'',type:(j['type']??'lent')=='borrowed'?DebtType.borrowed:DebtType.lent,amount:(j['amount']??0).toDouble(),settledAmount:(j['settledAmount']??0).toDouble(),category:j['category']??'مال',note:j['note']??'',createdAt:j['createdAt']??DateTime.now().millisecondsSinceEpoch,dueAt:j['dueAt'],settled:j['settled']??false); }

class Store{ static final I=Store._(); Store._(); List<Person> people=[]; List<Entry> entries=[]; String currency='دولار'; bool notifications=true, sounds=true, showSettled=true; String id()=>'${DateTime.now().millisecondsSinceEpoch}_${Random().nextInt(999999)}';
Future<void> load() async{ final p=await SharedPreferences.getInstance(); currency=p.getString('currency')??'دولار'; notifications=p.getBool('notifications')??true; sounds=p.getBool('sounds')??true; showSettled=p.getBool('showSettled')??true; final rp=p.getString('people'); if(rp!=null) people=(jsonDecode(rp) as List).map((e)=>Person.fromJson(Map<String,dynamic>.from(e))).toList(); final re=p.getString('entries'); if(re!=null) entries=(jsonDecode(re) as List).map((e)=>Entry.fromJson(Map<String,dynamic>.from(e))).toList(); }
Future<void> save() async{ final p=await SharedPreferences.getInstance(); await p.setString('currency',currency); await p.setBool('notifications',notifications); await p.setBool('sounds',sounds); await p.setBool('showSettled',showSettled); await p.setString('people',jsonEncode(people.map((e)=>e.toJson()).toList())); await p.setString('entries',jsonEncode(entries.map((e)=>e.toJson()).toList())); }
Person? person(String id){ try{return people.firstWhere((p)=>p.id==id);}catch(_){return null;} }
Person findOrCreate(String name){ final clean=name.trim(); for(final p in people){ if(p.name.trim().toLowerCase()==clean.toLowerCase()) return p; } final p=Person(id(),clean,DateTime.now().millisecondsSinceEpoch); people.add(p); return p; }
Future<void> add({required String personName,required DebtType type,required double amount,required String category,required String note,required int? dueAt,int? createdAt}) async{ final p=findOrCreate(personName); entries.add(Entry(id:id(),personId:p.id,type:type,amount:amount,settledAmount:0,category:category,note:note,createdAt:createdAt??DateTime.now().millisecondsSinceEpoch,dueAt:dueAt)); await save(); }
Future<void> deletePerson(String pid) async{ entries.removeWhere((e)=>e.personId==pid); people.removeWhere((p)=>p.id==pid); await save(); }
Future<void> deleteEntry(String id) async{ entries.removeWhere((e)=>e.id==id); await save(); }
Future<void> settle(String id,{double? amount}) async{ final e=entries.firstWhere((x)=>x.id==id); e.settledAmount+=amount??e.remaining; if(e.settledAmount>=e.amount){e.settledAmount=e.amount; e.settled=true;} await save(); }
List<Entry> entriesFor(String pid){ final l=entries.where((e)=>e.personId==pid && (showSettled || !e.settled)).toList(); l.sort((a,b)=>b.createdAt.compareTo(a.createdAt)); return l; }
double lent(String pid)=>entries.where((e)=>e.personId==pid&&e.type==DebtType.lent&&!e.settled).fold(0,(s,e)=>s+e.remaining); double borrowed(String pid)=>entries.where((e)=>e.personId==pid&&e.type==DebtType.borrowed&&!e.settled).fold(0,(s,e)=>s+e.remaining); double net(String pid)=>lent(pid)-borrowed(pid); double totalLent()=>people.fold(0,(s,p)=>s+lent(p.id)); double totalBorrowed()=>people.fold(0,(s,p)=>s+borrowed(p.id)); int lentCount()=>entries.where((e)=>e.type==DebtType.lent&&!e.settled).length; int borrowedCount()=>entries.where((e)=>e.type==DebtType.borrowed&&!e.settled).length; List<Person> activePeople(){ final ids=entries.map((e)=>e.personId).toSet(); final r=people.where((p)=>ids.contains(p.id)).toList(); r.sort((a,b){ int la=0,lb=0; for(final e in entries){ if(e.personId==a.id) la=max(la,e.createdAt); if(e.personId==b.id) lb=max(lb,e.createdAt);} return lb.compareTo(la);}); return r; }}

class HomeScreen extends StatefulWidget{ const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{ final s=Store.I; bool menu=false; Future<void> openWizard(DebtType t) async{ setState(()=>menu=false); await Navigator.push(context,MaterialPageRoute(builder:(_)=>EntryWizard(type:t))); setState((){}); }
@override Widget build(BuildContext context){ final people=s.activePeople(); return Scaffold(body:SafeArea(child:Stack(children:[Column(children:[top(),const AdMobBanner(),summary(),Expanded(child:people.isEmpty?empty():peopleList(people))]),addMenu()]))); }
Widget top()=>Container(height:64,color:darkPanel,child:Row(children:[IconButton(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const SettingsScreen())); setState((){});},icon:const Icon(Icons.settings,color:orangeSoft,size:32)),const Expanded(child:Center(child:Text('دفتر الديون',style:TextStyle(color:textMain,fontSize:27,fontWeight:FontWeight.w900)))),const SizedBox(width:48)]));
Widget summary(){ final net=s.totalLent()-s.totalBorrowed(); final c=s.currency; return Container(color:darkPanel2,padding:const EdgeInsets.symmetric(vertical:12),child:Column(children:[Row(children:[Expanded(child:Column(children:[const Text('لي عند الناس',style:TextStyle(color:redSoft,fontSize:20,fontWeight:FontWeight.w900)),Text('${money(s.totalLent())} $c',style:const TextStyle(color:redSoft,fontSize:25,fontWeight:FontWeight.w900)),Text('${s.lentCount()} عملية',style:const TextStyle(color:redSoft,fontSize:17,fontWeight:FontWeight.w700))])),Container(width:1,height:72,color:divider),Expanded(child:Column(children:[const Text('علي للناس',style:TextStyle(color:greenSoft,fontSize:20,fontWeight:FontWeight.w900)),Text('${money(s.totalBorrowed())} $c',style:const TextStyle(color:greenSoft,fontSize:25,fontWeight:FontWeight.w900)),Text('${s.borrowedCount()} عملية',style:const TextStyle(color:greenSoft,fontSize:17,fontWeight:FontWeight.w700))]))]),const SizedBox(height:8),Text(net==0?'الصافي: لا يوجد رصيد':net>0?'الصافي: لك ${money(net.abs())} $c':'الصافي: عليك ${money(net.abs())} $c',style:TextStyle(color:net==0?textSoft:net>0?redSoft:greenSoft,fontWeight:FontWeight.w900,fontSize:17))])); }
Widget empty()=>Center(child:Text('لا توجد ديون بعد\nاضغط + لإضافة أول عملية',textAlign:TextAlign.center,style:TextStyle(color:textSoft.withOpacity(.85),fontSize:20,fontWeight:FontWeight.w800,height:1.8)));
Widget peopleList(List<Person> ps)=>ListView.builder(padding:const EdgeInsets.only(top:10,bottom:100),itemCount:ps.length,itemBuilder:(_,i){ final p=ps[i]; final net=s.net(p.id); final color=net>=0?redSoft:greenSoft; final label=net==0?'تمت التسوية':net>0?'لك عنده ${money(net.abs())} ${s.currency}':'عليك له ${money(net.abs())} ${s.currency}'; final count=s.entries.where((e)=>e.personId==p.id).length; return InkWell(onTap:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>PersonScreen(person:p))); setState((){});},child:Container(padding:const EdgeInsets.symmetric(horizontal:18,vertical:14),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:divider,width:.7))),child:Row(children:[Container(width:60,height:60,decoration:const BoxDecoration(shape:BoxShape.circle,color:whiteSoft),child:const Icon(Icons.add,color:orangeSoft,size:30)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name,style:const TextStyle(color:textMain,fontSize:22,fontWeight:FontWeight.w900)),Text(label,style:TextStyle(color:color,fontSize:16,fontWeight:FontWeight.w900)),Text('$count عملية',style:const TextStyle(color:textSoft,fontSize:13,fontWeight:FontWeight.w700))])),PopupMenuButton<String>(color:darkPanel2,icon:Icon(Icons.more_vert_rounded,color:color),onSelected:(v){if(v=='delete')deletePerson(p);},itemBuilder:(_)=>const[PopupMenuItem(value:'delete',child:Text('حذف الشخص بالكامل',style:TextStyle(color:textMain)))]),Icon(Icons.chevron_left_rounded,color:color)])) );});
Future<void> deletePerson(Person p)async{ final count=s.entries.where((e)=>e.personId==p.id).length; final ok=await showDialog<bool>(context:context,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:darkPanel,title:const Text('حذف الشخص بالكامل',style:TextStyle(color:textMain)),content:Text('سيتم حذف ${p.name} وكل عملياته وعددها $count عملية. هل أنت متأكد؟',style:const TextStyle(color:textSoft,height:1.6,fontWeight:FontWeight.w700)),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(style:FilledButton.styleFrom(backgroundColor:redSoft),onPressed:()=>Navigator.pop(context,true),child:const Text('حذف نهائي'))]))); if(ok==true){ await s.deletePerson(p.id); await appFeedback('delete.wav'); if(!mounted)return; setState((){}); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تم حذف ${p.name} بالكامل'))); } }
Widget addMenu()=>Positioned(bottom:22,left:0,right:0,child:SizedBox(height:185,child:Stack(alignment:Alignment.bottomCenter,children:[if(menu)CustomPaint(size:const Size(260,160),painter:ArcPainter()),if(menu)Positioned(bottom:92,right:MediaQuery.of(context).size.width/2+28,child:bubble('أعطيت',Icons.arrow_upward_rounded,redSoft,()=>openWizard(DebtType.lent))),if(menu)Positioned(bottom:92,left:MediaQuery.of(context).size.width/2+28,child:bubble('أخذت',Icons.arrow_downward_rounded,greenSoft,()=>openWizard(DebtType.borrowed))),Positioned(bottom:0,child:GestureDetector(onTap:()=>setState(()=>menu=!menu),child:Container(width:72,height:72,decoration:const BoxDecoration(shape:BoxShape.circle,color:orangeSoft),child:Icon(menu?Icons.close_rounded:Icons.add_rounded,color:Colors.white,size:42))))])));
Widget bubble(String t,IconData ic,Color color,VoidCallback f)=>GestureDetector(onTap:f,child:Column(children:[Container(width:66,height:66,decoration:BoxDecoration(shape:BoxShape.circle,color:color),child:Icon(ic,color:Colors.white,size:34)),const SizedBox(height:3),Text(t,style:const TextStyle(color:textMain,fontWeight:FontWeight.w900,fontSize:14))])); }
class ArcPainter extends CustomPainter{ @override void paint(Canvas c,Size s){ final p=Paint()..color=Colors.white.withOpacity(.16); c.drawArc(Rect.fromCenter(center:Offset(s.width/2,s.height+25),width:280,height:240),pi,pi,true,p); } @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false; }

class EntryWizard extends StatefulWidget{ final DebtType type; const EntryWizard({super.key,required this.type}); @override State<EntryWizard> createState()=>_EntryWizardState(); }
class _EntryWizardState extends State<EntryWizard>{ final s=Store.I; final name=TextEditingController(); final note=TextEditingController(); String amount='',category='مال'; int step=0,due=0; DateTime selectedDate=DateTime.now(); Color get color=>widget.type==DebtType.lent?redSoft:greenSoft; String get title=>widget.type==DebtType.lent?'أعطيت دين':'أخذت دين'; int? get dueAt{ final n=DateTime.now(); if(due==1)return n.add(const Duration(days:7)).millisecondsSinceEpoch; if(due==2)return n.add(const Duration(days:14)).millisecondsSinceEpoch; if(due==3)return DateTime(n.year,n.month+1,n.day).millisecondsSinceEpoch; return null; }
@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[bar(),Expanded(child:step==0?personStep():amountStep())])));
Widget bar()=>Container(height:62,color:darkPanel,child:Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:Icon(Icons.arrow_back_rounded,color:color,size:34)),Expanded(child:Center(child:Text(title,style:const TextStyle(color:textMain,fontSize:22,fontWeight:FontWeight.w900)))),TextButton(onPressed:step==0?next:save,child:Text(step==0?'التالي':'حفظ',style:TextStyle(color:color,fontSize:18,fontWeight:FontWeight.w900)))]));
Widget personStep(){ final q=name.text.trim(); final sug=s.people.where((p)=>q.isNotEmpty&&p.name.contains(q)).toList(); return Column(children:[Container(color:color,padding:const EdgeInsets.all(14),child:TextField(controller:name,autofocus:true,style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900),decoration:InputDecoration(hintText:widget.type==DebtType.lent?'لمن أعطيت الدين؟':'من الذي أخذت منه؟',hintStyle:TextStyle(color:Colors.white.withOpacity(.55),fontWeight:FontWeight.w800),border:InputBorder.none,prefixIcon:const Icon(Icons.person,color:Colors.white)),onChanged:(_)=>setState((){}),onSubmitted:(_)=>next())),Expanded(child:sug.isEmpty?Center(child:Text('اكتب اسم الشخص\nسيتم إنشاؤه تلقائيًا إذا كان جديدًا',textAlign:TextAlign.center,style:TextStyle(color:textSoft.withOpacity(.85),fontSize:19,fontWeight:FontWeight.w800,height:1.8))):ListView(children:sug.map((p)=>ListTile(title:Text(p.name,style:const TextStyle(color:textMain,fontWeight:FontWeight.w900)),leading:const CircleAvatar(backgroundColor:whiteSoft,child:Icon(Icons.person,color:orangeSoft)),onTap:(){name.text=p.name; next();})).toList()))]); }
Widget amountStep()=>Column(children:[Expanded(child:SingleChildScrollView(child:Column(children:[const SizedBox(height:20),Container(width:76,height:76,decoration:const BoxDecoration(shape:BoxShape.circle,color:whiteSoft),child:const Icon(Icons.add,color:orangeSoft,size:38)),const SizedBox(height:8),Text(name.text.trim(),style:const TextStyle(color:textMain,fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:14),catRow(),const SizedBox(height:16),Text(amount.isEmpty?'0 ${s.currency}':'${amount.endsWith('.')?amount.substring(0,amount.length-1):amount} ${s.currency}',style:const TextStyle(color:textMain,fontSize:40,fontWeight:FontWeight.w900)),Padding(padding:const EdgeInsets.symmetric(horizontal:28,vertical:8),child:TextField(controller:note,textAlign:TextAlign.center,style:const TextStyle(color:textMain),decoration:const InputDecoration(hintText:'ملاحظة...',hintStyle:TextStyle(color:textSoft,fontWeight:FontWeight.w800),border:InputBorder.none))),dateButton(),const SizedBox(height:8),dueButtons()]))),keypad()]);
Widget catRow()=>Row(mainAxisAlignment:MainAxisAlignment.center,children:[cat('مال',Icons.attach_money_rounded),const SizedBox(width:12),cat('بضاعة',Icons.inventory_2_outlined),const SizedBox(width:12),cat('أخرى',Icons.category_outlined)]);
Widget cat(String n,IconData ic){ final a=category==n; return GestureDetector(onTap:()=>setState(()=>category=n),child:Container(width:a?68:52,height:a?68:52,decoration:BoxDecoration(shape:BoxShape.circle,color:a?color:Colors.transparent,border:Border.all(color:color,width:2)),child:Icon(ic,color:a?Colors.white:color,size:a?35:26))); }
Widget dateButton()=>Padding(padding:const EdgeInsets.symmetric(horizontal:24,vertical:4),child:InkWell(borderRadius:BorderRadius.circular(18),onTap:pickDate,child:Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:14,vertical:12),decoration:BoxDecoration(color:darkPanel2,borderRadius:BorderRadius.circular(18),border:Border.all(color:blueSoft.withOpacity(.55))),child:Row(children:[const Icon(Icons.calendar_month_rounded,color:blueSoft),const SizedBox(width:10),const Expanded(child:Text('تاريخ العملية',style:TextStyle(color:textMain,fontWeight:FontWeight.w900))),Text(dateOnly(selectedDate.millisecondsSinceEpoch),style:const TextStyle(color:blueSoft,fontWeight:FontWeight.w900))]))));
Future<void> pickDate()async{ final p=await showDatePicker(context:context,initialDate:selectedDate,firstDate:DateTime(2000),lastDate:DateTime(2100),builder:(context,child)=>Theme(data:ThemeData.dark().copyWith(colorScheme:const ColorScheme.dark(primary:orangeSoft,onPrimary:Colors.white,surface:darkPanel,onSurface:textMain)),child:child!)); if(p!=null){ setState(()=>selectedDate=DateTime(p.year,p.month,p.day,DateTime.now().hour,DateTime.now().minute)); } }
Widget dueButtons(){ final opts=[['بدون',0],['1 أسبوع',1],['2 أسبوع',2],['1 شهر',3]]; return Wrap(spacing:10,runSpacing:8,alignment:WrapAlignment.center,children:opts.map((o){ final a=due==o[1]; return ChoiceChip(selected:a,selectedColor:blueSoft,backgroundColor:Colors.transparent,side:const BorderSide(color:blueSoft),label:Text(o[0].toString(),style:TextStyle(color:a?Colors.white:blueSoft,fontWeight:FontWeight.w900)),onSelected:(_)=>setState(()=>due=o[1] as int));}).toList()); }
Widget keypad(){ final ks=['1','2','3','4','5','6','7','8','9','.','0','⌫']; return Container(color:whiteSoft,child:GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:ks.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,childAspectRatio:2.15),itemBuilder:(_,i){ final k=ks[i]; return InkWell(onTap:()=>press(k),child:Container(decoration:BoxDecoration(border:Border.all(color:Colors.black.withOpacity(.08))),child:Center(child:Text(k,style:TextStyle(color:Colors.black.withOpacity(.62),fontSize:31,fontWeight:FontWeight.w500))))); })); }
void press(String k){ setState((){ if(k=='⌫'){ if(amount.isNotEmpty) amount=amount.substring(0,amount.length-1); return;} if(k=='.'&&amount.contains('.'))return; if(amount.length>=10)return; amount+=k; }); }
void next(){ if(name.text.trim().isEmpty)return; setState(()=>step=1); }
Future<void> save() async{ final a=double.tryParse(amount.endsWith('.')?amount.substring(0,amount.length-1):amount)??0; if(name.text.trim().isEmpty||a<=0)return; await s.add(personName:name.text.trim(),type:widget.type,amount:a,category:category,note:note.text.trim(),dueAt:dueAt,createdAt:selectedDate.millisecondsSinceEpoch); await appFeedback('coin.wav'); if(mounted) Navigator.pop(context); }}

class PersonScreen extends StatefulWidget{ final Person person; const PersonScreen({super.key,required this.person}); @override State<PersonScreen> createState()=>_PersonScreenState(); }
class _PersonScreenState extends State<PersonScreen>{ final s=Store.I; @override Widget build(BuildContext context){ final es=s.entriesFor(widget.person.id); final net=s.net(widget.person.id); return Scaffold(body:SafeArea(child:Stack(children:[Column(children:[top(),const AdMobBanner(),header(net),section(net),Expanded(child:es.isEmpty?const Center(child:Text('لا توجد عمليات',style:TextStyle(color:textSoft))):ListView.builder(padding:const EdgeInsets.only(bottom:100),itemCount:es.length,itemBuilder:(_,i)=>tile(es[i])))]),Positioned(bottom:22,left:0,right:0,child:Center(child:GestureDetector(onTap:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>EntryWizard(type:DebtType.lent))); setState((){});},child:Container(width:72,height:72,decoration:const BoxDecoration(shape:BoxShape.circle,color:orangeSoft),child:const Icon(Icons.add,color:Colors.white,size:42)))))])) ); }
Widget top()=>Container(height:60,color:darkPanel,child:Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,color:orangeSoft,size:34)),Expanded(child:Center(child:Text(widget.person.name,style:const TextStyle(color:textMain,fontSize:22,fontWeight:FontWeight.w900)))),PopupMenuButton<String>(color:darkPanel2,icon:const Icon(Icons.more_horiz_rounded,color:textMain),onSelected:(v){if(v=='share')shareStatement();},itemBuilder:(_)=>const[PopupMenuItem(value:'share',child:Text('مشاركة كشف الحساب',style:TextStyle(color:textMain)))]) ]));
Widget header(double net)=>Container(width:double.infinity,color:darkPanel2,padding:const EdgeInsets.symmetric(vertical:22),child:Column(children:[Container(width:94,height:94,decoration:const BoxDecoration(shape:BoxShape.circle,color:whiteSoft),child:const Icon(Icons.person_add_alt_1_rounded,color:orangeSoft,size:45)),const SizedBox(height:8),Text(net==0?'لا يوجد رصيد':net>0?'لك عنده ${money(net.abs())} ${s.currency}':'عليك له ${money(net.abs())} ${s.currency}',style:TextStyle(color:net==0?textSoft:net>0?redSoft:greenSoft,fontSize:20,fontWeight:FontWeight.w900))]));
Widget section(double net)=>Container(width:double.infinity,color:Colors.black.withOpacity(.25),padding:const EdgeInsets.symmetric(horizontal:14,vertical:8),child:Text(net<0?'أنت مدين لـ ${widget.person.name}':'عمليات ${widget.person.name}',style:const TextStyle(color:textMain,fontWeight:FontWeight.w900,fontSize:15)));
Widget tile(Entry e){ final isL=e.type==DebtType.lent; final color=isL?redSoft:greenSoft; final title=isL?'أعطيت ${widget.person.name}':'أخذت من ${widget.person.name}'; final due=e.dueAt==null?'':' - مستحق ${dateOnly(e.dueAt!)}'; final sub=[if(e.note.isNotEmpty)e.note,'تاريخ العملية ${dateOnly(e.createdAt)}',ago(e.createdAt),if(e.settled)'تمت التسوية',if(!e.settled&&e.settledAmount>0)'مسدد جزئيًا ${money(e.settledAmount)} ${s.currency}'].join(' | '); return Dismissible(key:ValueKey(e.id),background:Container(color:greenSoft,padding:const EdgeInsets.symmetric(horizontal:22),alignment:Alignment.centerRight,child:const SizedBox(width:120,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.check_circle_rounded,color:Colors.white,size:32),SizedBox(width:8),Text('تسوية',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900))]))),secondaryBackground:Container(color:redSoft,padding:const EdgeInsets.symmetric(horizontal:22),alignment:Alignment.centerLeft,child:const SizedBox(width:120,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text('حذف',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),SizedBox(width:8),Icon(Icons.delete_rounded,color:Colors.white,size:32)]))),confirmDismiss:(d)async{ if(d==DismissDirection.startToEnd){ await settleDialog(e); return false;} return await deleteDialog(e);},child:Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:13),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:divider,width:.7))),child:Row(children:[Container(width:48,height:48,decoration:const BoxDecoration(shape:BoxShape.circle,color:yellowSoft),child:Icon(e.category=='مال'?Icons.attach_money_rounded:e.category=='بضاعة'?Icons.inventory_2_outlined:Icons.category_outlined,color:Colors.white)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:textMain,fontWeight:FontWeight.w900,fontSize:16)),Text('${money(e.remaining)} ${s.currency}$due',style:TextStyle(color:color,fontWeight:FontWeight.w900,fontSize:16)),if(sub.isNotEmpty)Text(sub,style:const TextStyle(color:textSoft,fontWeight:FontWeight.w700,fontSize:12))]))]))); }
Future<void> settleDialog(Entry e)async{ final c=TextEditingController(text:money(e.remaining)); final ok=await showDialog<bool>(context:context,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:darkPanel,title:const Text('تسوية العملية',style:TextStyle(color:textMain)),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),style:const TextStyle(color:textMain),decoration:const InputDecoration(hintText:'المبلغ المسدد')),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('تسوية'))]))); if(ok==true){ await s.settle(e.id,amount:double.tryParse(c.text.replaceAll(',','.'))??e.remaining); await appFeedback('settle.wav'); setState((){});} }
Future<bool> deleteDialog(Entry e)async{ final ok=await showDialog<bool>(context:context,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:AlertDialog(backgroundColor:darkPanel,title:const Text('حذف العملية',style:TextStyle(color:textMain)),content:const Text('هل تريد حذف هذه العملية؟',style:TextStyle(color:textSoft)),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حذف'))]))); if(ok==true){await s.deleteEntry(e.id); await appFeedback('delete.wav'); setState((){}); return true;} return false; }
void shareStatement(){
  final all=s.entries.where((e)=>e.personId==widget.person.id).toList()..sort((a,b)=>b.createdAt.compareTo(a.createdAt));
  final active=all.where((e)=>!e.settled).toList();
  final totalLent=active.where((e)=>e.type==DebtType.lent).fold<double>(0,(sum,e)=>sum+e.remaining);
  final totalBorrowed=active.where((e)=>e.type==DebtType.borrowed).fold<double>(0,(sum,e)=>sum+e.remaining);
  final n=totalLent-totalBorrowed;
  final lines=<String>[
    'دفتر الديون',
    'كشف حساب: ${widget.person.name}',
    'تاريخ الكشف: ${dateOnly(DateTime.now().millisecondsSinceEpoch)}',
    '------------------------------',
    'لي عنده: ${money(totalLent)} ${s.currency}',
    'علي له: ${money(totalBorrowed)} ${s.currency}',
    n==0?'الصافي: لا يوجد رصيد':n>0?'الصافي: لك ${money(n.abs())} ${s.currency}':'الصافي: عليك ${money(n.abs())} ${s.currency}',
    '------------------------------',
    'تفاصيل العمليات:',
  ];
  if(all.isEmpty){
    lines.add('لا توجد عمليات مسجلة.');
  } else {
    for(var i=0;i<all.length;i++){
      final e=all[i];
      final action=e.type==DebtType.lent?'أعطيت':'أخذت';
      final status=e.settled?'مسددة بالكامل':e.settledAmount>0?'مسددة جزئيًا':'غير مسددة';
      lines.add('${i+1}) $action');
      lines.add('   المبلغ الأصلي: ${money(e.amount)} ${s.currency}');
      lines.add('   المسدد: ${money(e.settledAmount)} ${s.currency}');
      lines.add('   المتبقي: ${money(e.remaining)} ${s.currency}');
      lines.add('   الحالة: $status');
      lines.add('   تاريخ العملية: ${dateOnly(e.createdAt)}');
      if(e.dueAt!=null) lines.add('   موعد السداد: ${dateOnly(e.dueAt!)}');
      if(e.note.trim().isNotEmpty) lines.add('   ملاحظة: ${e.note.trim()}');
      lines.add('------------------------------');
    }
  }
  lines.add('تم إنشاء الكشف من تطبيق دفتر الديون');
  Share.share(lines.join('\n'),subject:'كشف حساب ${widget.person.name}');
}}

class SettingsScreen extends StatefulWidget{ const SettingsScreen({super.key}); @override State<SettingsScreen> createState()=>_SettingsScreenState(); }
class _SettingsScreenState extends State<SettingsScreen>{ final s=Store.I; final currencies=const['دولار','دينار','ريال','جنيه','درهم']; @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[top(),const AdMobBanner(),Expanded(child:ListView(children:[softTile(Icons.attach_money_rounded,greenSoft,'العملة',trailingText:s.currency,onTap:chooseCurrency),softTile(Icons.notifications_active_rounded,redSoft,'تنبيهات الاستحقاق',trailing:Switch(value:s.notifications,onChanged:(v)async{setState(()=>s.notifications=v);await s.save();})),softTile(Icons.volume_up_rounded,orangeSoft,'الأصوات',trailing:Switch(value:s.sounds,onChanged:(v)async{setState(()=>s.sounds=v);await s.save();})),softTile(Icons.music_note_rounded,yellowSoft,'تجربة الصوت',trailingText:'تشغيل',onTap:()=>appFeedback('coin.wav')),softTile(Icons.done_all_rounded,blueSoft,'إظهار العمليات المسددة',trailing:Switch(value:s.showSettled,onChanged:(v)async{setState(()=>s.showSettled=v);await s.save();})),softTile(Icons.backup_rounded,cyanSoft,'نسخ احتياطي',trailingText:'قريبًا'),softTile(Icons.table_chart_rounded,greenSoft,'تصدير Excel',trailingText:'قريبًا'),softTile(Icons.picture_as_pdf_rounded,redSoft,'تصدير PDF',trailingText:'قريبًا'),softTile(Icons.feedback_rounded,yellowSoft,'إرسال ملاحظات')]))])));
Widget top()=>Container(height:62,color:darkPanel,child:Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,color:orangeSoft,size:34)),const Expanded(child:Center(child:Text('الإعدادات',style:TextStyle(color:textMain,fontSize:24,fontWeight:FontWeight.w900)))),const SizedBox(width:48)]));
Widget softTile(IconData ic,Color color,String title,{String? trailingText,Widget? trailing,VoidCallback? onTap})=>InkWell(onTap:onTap,child:Container(padding:const EdgeInsets.symmetric(horizontal:14,vertical:11),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:divider,width:.6))),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(shape:BoxShape.circle,color:color),child:Icon(ic,color:Colors.white)),const SizedBox(width:14),Expanded(child:Text(title,style:const TextStyle(color:textMain,fontSize:18,fontWeight:FontWeight.w900))),if(trailing!=null)trailing,if(trailingText!=null)Text(trailingText,style:const TextStyle(color:textSoft,fontSize:17,fontWeight:FontWeight.w800)),if(onTap!=null)const Icon(Icons.chevron_left_rounded,color:textMain)])));
Future<void> chooseCurrency()async{ final selected=await showModalBottomSheet<String>(context:context,backgroundColor:darkPanel,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const Padding(padding:EdgeInsets.all(16),child:Text('اختر العملة',style:TextStyle(color:textMain,fontSize:22,fontWeight:FontWeight.w900))),...currencies.map((c)=>ListTile(title:Text(c,style:const TextStyle(color:textMain,fontWeight:FontWeight.w900,fontSize:18)),leading:Icon(c==s.currency?Icons.check_circle:Icons.circle_outlined,color:greenSoft),onTap:()=>Navigator.pop(context,c)))])))); if(selected!=null){s.currency=selected; await s.save(); setState((){});} }}
